### PR TITLE
fix(po-format): remove duplicated references when lineNumbers is false

### LINKED ISSUE #2405: Reduce PO catalog comments changes for cleaner source control
### Problem Description

Keeping PO files in Git can result in thousands of changed lines with minimal changes to translations after every extraction. The source of most are comments with file paths and line numbers. I think it's possible to disable comments altogether but I do want to keep the reference to the file name.

In essence I want to transform this:

```po
#: survey/config/project-survey.ts:12
#: survey/config/project-survey.ts:20
#: survey/config/project-survey.ts:55
#: survey/config/user-survey.ts:33
#: survey/config/user-survey.ts:46
msgid "Don’t know"
msgstr "Ne vem"
```

Into this:

```po
#: survey/config/project-survey.ts
#: survey/config/user-survey.ts
msgid "Don’t know"
msgstr "Ne vem"
```

### Proposed Solution

This config will get rid of the line numbers:

```js
import { defineConfig } from '@lingui/cli'
import { formatter } from '@lingui/format-po'
export default defineConfig({
  format: formatter({ lineNumbers: false, printPlaceholdersInComments: false }),
// ...
})
```

But you still get duplicated lines if the same translation appears multiple times in the same file. I think the PO extractor should automatically remove duplicated comment lines regardless of there being an option or not. 

Right now I'm using a post-extract script to strip unwanted lines.

__clean-po-files.sh__

```sh
#!/bin/sh

wd=$(pwd)

for po in "$wd"/src/locales/*.po; do
  uniq "$po" > "${po}.new"
  rm "$po"
  mv "${po}.new" "$po"
done
```

__package.json__

```json
{
  "scripts": {
    "extract": "lingui extract && ./clean-po-files.sh"
  }
}
```

### Alternatives Considered

I'm using the post-extract script for now and that works fine.

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by itsyoboieltr**
# Description

[//]: # (Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.)

When `lineNumbers: false` is used, extracted PO catalogs currently keep duplicate `#:` reference lines if the same message appears multiple times in the same file. That creates unnecessary diff noise in source control even though the line numbers have already been intentionally removed.

This PR reduces that churn by deduplicating file-only references while preserving their original order.

Changes:
  - deduplicate references in `@lingui/format-po` when `lineNumbers: false`
  - deduplicate references in `@lingui/format-po-gettext` for the `mergePlurals: true` path, where merged plural entries could reintroduce duplicate file-only references
  - add regression tests for both cases

This keeps the existing behavior unchanged when line numbers are enabled, and only removes repeated file references once multiple locations have collapsed to the same path.

## Types of changes

[//]: # (What types of changes does your code introduce to Lingui?)
[//]: # (_Put an `x` in the boxes that apply_)

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update
- [ ] Examples update

Fixes https://github.com/lingui/js-lingui/issues/2405

## Checklist

[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._)

- [x] I have read the [CONTRIBUTING](https://github.com/lingui/js-lingui/blob/main/CONTRIBUTING.md) and [CODE_OF_CONDUCT](https://github.com/lingui/js-lingui/blob/main/CODE_OF_CONDUCT.md) docs
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added the necessary documentation (if appropriate)

### CODE REVIEW

**Comment by timofei-iatsenko** [comment]
@itsyoboieltr hey, all current development happened in the `next` branch, could you change the basse of your PR to that?

File: packages/format-po-gettext/src/po-gettext.ts [hunk 1]
```diff
@@ -433,8 +433,11 @@ function mergeDuplicatePluralEntries(
         ctxPrefix
       )
 
-      // Merge references
-      mergedItem.references = duplicateItems.flatMap((item) => item.references)
+      // Merge references. When line numbers are disabled, preserve only unique file paths.
+      mergedItem.references =
+        options.lineNumbers === false
+          ? [...new Set(duplicateItems.flatMap((item) => item.references))]
+          : duplicateItems.flatMap((item) => item.references)
```
Comment (timofei-iatsenko) [inline packages/format-po-gettext/src/po-gettext.ts]: Let's avoid the branching here and just leave the `[...new Set(duplicateItems.flatMap((item) => item.references))]` the same way as in the po formatter.

**Review by timofei-iatsenko — CHANGES_REQUESTED** [review]

File: packages/format-po-gettext/src/po-gettext.ts (hunk 1 above)
Comment (itsyoboieltr) [reply packages/format-po-gettext/src/po-gettext.ts]: fixed

**Comment by itsyoboieltr** [comment]
@timofei-iatsenko I reset the branch onto next, reapplied the fix there, and force-pushed. The PR should now be clean against next.

**Review by timofei-iatsenko — APPROVED** [review]
