### PR TITLE
fix(macro): JS macros don't strip non-essential props in production

### LINKED ISSUE #1379: JS macro don't strip non-essential props on production.
The JSX macro (`<Trans>`, `<Plural>`, etc) has a feature, when you set `NODE_ENV === 'production'` it strips properties needed only for translators and saving the final bundle size. 

Unlike JSX macro, js doesn't do that. Even though it's mentioned in the docs. It seems it was never implemented. 

By the way, SWC Plugin implementing both optimization 💪

### PR DESCRIPTION
**Pull request by Martin005**
# Description
This PR fixes #1379.
The current implementation of macros was stripping non-essential props (`message` and `comment`) only in JSX macros, not in JS macros. This PR brings the stripping of these props in JS macros on par with JSX macros.

There are several changes to the `macroJs.js` file, but most of them are changes from Prettier. The only change to code relating to this bug is the implementation at the end of the `processDescriptor()` function.

## Types of changes

[//]: # (What types of changes does your code introduce to Lingui?)
[//]: # (_Put an `x` in the boxes that apply_)

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## Checklist

[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._)

- [x] I have read the [CONTRIBUTING](https://github.com/lingui/js-lingui/blob/main/CONTRIBUTING.md) and [CODE_OF_CONDUCT](https://github.com/lingui/js-lingui/blob/main/CODE_OF_CONDUCT.md) docs
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

File: packages/macro/src/macroJs.ts [hunk 1]
```diff
@@ -159,16 +173,29 @@ export default class MacroJs {
     // reset the expression counter
     this._expressionIndex = makeCounter()
 
-    const descriptor = this.processDescriptor(path.node.arguments[0])
+    let descriptor = this.processDescriptor(path.node.arguments[0])
+
+    if (process.env.NODE_ENV === "production") {
+      descriptor = this.stripNonEssentialProps(descriptor)
+    }
```
Comment (thekip) [inline packages/macro/src/macroJs.ts:180]: Could you move this check into `processDescriptor` method and avoid code duplication in `replaceDefineMessage` and `replaceTAsFunction`?

**Review by andrii-bodnar — APPROVED** [review]
